item {
  id: 1
  name: 'Neutrophils'
}

item {
  id: 2
  name: 'Lymphocytes'
}

item {
  id: 3
  name: 'Eosinophils'
}

item {
  id: 4
  name: 'Monocytes'
}

item {
  id: 5
  name: 'Basophils'
}
item {
  id: 6
  name: 'None'
}
